exclude: >
  (?x)^(
      src/pythonfinder/_vendor/.*\.py
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-use-type-annotations

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.263
    hooks:
      - id: ruff
        args: [ --exit-non-zero-on-fix ]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
